version: '3'

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.30.0/24

  db-net:
    driver: bridge

#   reversed-proxy-network:
#     external:
#       name: proxy-network

services:
  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: csfeng0826/jupyter:latest

  postgres:
    image: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
      - POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
    entrypoint: /bin/sh -c
    command: ["${JUPYTERHUB_INTERNAL_POSTGRES} && docker-entrypoint.sh postgres"]
    networks:
      - db-net

  jupyterhub:
    build: ./jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DATA_PATH_HOST}/jupyterhub/data/:/data
      - ${DATA_PATH_HOST}/jupyterhub/user-data/:/user-data
      - ./jupyterhub/admin.txt:/root/.jupyter/admin.txt
    ports:
      - "9991:80"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
      - db-net
#       - reversed-proxy-network
  
  jupyter-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
      - default
