version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
      - POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
    entrypoint: /bin/sh -c
    command: ["${JUPYTERHUB_INTERNAL_POSTGRES} && docker-entrypoint.sh postgres"]

  jupyterhub:
    build: ./jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DATA_PATH_HOST}/jupyterhub/data/:/data
      - ${DATA_PATH_HOST}/jupyterhub/user-data/:/user-data
      - ./jupyterhub/admin.txt:/root/.jupyter/admin.txt
    ports:
      - "${JUPYTERHUB_PORT}:80"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default